/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { useLenis } from 'lenis/react';
import { LoopOnce } from 'three';

export function Cube(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/box.glb');
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    const action = actions['Action'];
    if (action) {
      action.clampWhenFinished = true;
      action.setLoop(LoopOnce);
    }
  }, [actions]);

  const animationPlayedRef = useRef(false);
  useLenis(
    (lenis) => {
      const progress = lenis.progress || 0;
      if (progress >= 0.715 && !animationPlayedRef.current) {
        actions['Action']?.play();
        animationPlayedRef.current = true;
      }
    },
    [actions]
  );

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Cube"
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={nodes.Cube.material}
          scale={1.453}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/box.glb');
