/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF, PerspectiveCamera, useAnimations, PresentationControls } from '@react-three/drei';
import { useEffect } from 'react';
import { useFrame } from '@react-three/fiber';
import { useLenis } from 'lenis/react';
import { mapProgress } from '../../../utils/progress';
import TopPlane from './TopPlane';
import { Neo } from './NeonLight';

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/20.glb');
  const { actions } = useAnimations(animations, group);
  useEffect(() => void (actions['Animation'].play().paused = true), [actions]);
  useLenis((lenis) => {
    const progress = lenis.progress || 0;
    const action = actions['Animation'];

    action.time = action.getClip().duration * Math.max(0.01, mapProgress(progress, 0, 0.5));
  });
  useFrame((state) => {
    // group.current.position.y = Math.sin(state.clock.elapsedTime)
    // console.log(state.camera)
  });
  return (
    <>
      <group ref={group} {...props} dispose={null}>
        <group name="Scene1">
          <group name="Empty007" scale={7.495}>
            <group name="Empty005" position={[0, 0, 0.145]} rotation={[-2.689, 0, 0]} scale={0.133}>
              <group name="Empty003" position={[-2.623, 2.813, 0.632]} scale={1.687}>
                <mesh
                  name="右_VID1"
                  castShadow
                  receiveShadow
                  geometry={nodes.右_VID1.geometry}
                  material={materials['Mat_IOR_1.0_Dispersion分散0']}
                  position={[0, 0, -0.003]}
                  rotation={[-0.169, -0.108, -0.024]}
                  scale={-2.197}
                />
                <mesh
                  name="右_VID2"
                  castShadow
                  receiveShadow
                  geometry={nodes.右_VID2.geometry}
                  material={materials['Mat_IOR_1.0_Dispersion分散0']}
                  position={[0.008, 0, -0.043]}
                  rotation={[-0.169, -0.108, -0.024]}
                  scale={-2.197}
                />
                <mesh
                  name="右_中间波导层"
                  castShadow
                  receiveShadow
                  geometry={nodes.右_中间波导层.geometry}
                  material={materials['Mat_IOR_1.0_Dispersion分散0']}
                  position={[0.003, 0, -0.034]}
                  rotation={[-0.169, -0.108, -0.024]}
                  scale={-2.197}
                />
              </group>
              <group name="Empty004" position={[2.215, 2.882, 0.677]} scale={2.163}>
                <mesh
                  name="左_VID1001"
                  castShadow
                  receiveShadow
                  geometry={nodes.左_VID1001.geometry}
                  material={materials['Mat_IOR_1.0_Dispersion分散0']}
                  position={[0, 0, -0.002]}
                  rotation={[-0.169, -0.108, -0.024]}
                  scale={[-1.713, -1.714, -1.714]}
                />
                <mesh
                  name="左_VID2001"
                  castShadow
                  receiveShadow
                  geometry={nodes.左_VID2001.geometry}
                  material={materials['Mat_IOR_1.0_Dispersion分散0']}
                  position={[-0.006, 0, -0.034]}
                  rotation={[-0.169, -0.108, -0.024]}
                  scale={[-1.713, -1.714, -1.714]}
                />
                <mesh
                  name="左_中间波导层001"
                  castShadow
                  receiveShadow
                  geometry={nodes.左_中间波导层001.geometry}
                  material={materials['Mat_IOR_1.0_Dispersion分散0']}
                  position={[-0.002, 0, -0.014]}
                  rotation={[-0.169, -0.108, -0.024]}
                  scale={[-1.713, -1.714, -1.714]}
                />
              </group>
              <mesh
                name="Object_12004"
                castShadow
                receiveShadow
                geometry={nodes.Object_12004.geometry}
                material={materials.material_3}
                position={[-0.26, 2.252, -0.906]}
              />
              <mesh
                name="Object_12005"
                castShadow
                receiveShadow
                geometry={nodes.Object_12005.geometry}
                material={materials.material_3}
                position={[-0.26, 2.252, -0.906]}
              />
              <mesh
                name="Object_4004"
                castShadow
                receiveShadow
                geometry={nodes.Object_4004.geometry}
                material={materials['002_Nose']}
                position={[-0.26, 2.252, -0.906]}
              />
              <mesh
                name="Object_6002"
                castShadow
                receiveShadow
                geometry={nodes.Object_6002.geometry}
                material={materials.material_3}
                position={[-0.26, 2.252, -0.906]}
              />
              <mesh
                name="前镜框"
                castShadow
                receiveShadow
                geometry={nodes.前镜框.geometry}
                material={materials.黑边框}
                position={[-0.171, 2.932, 0.414]}
              />
              <mesh
                name="右指示灯"
                castShadow
                receiveShadow
                geometry={nodes.右指示灯.geometry}
                material={materials['sunglass.002']}
                position={[-0.196, 3.702, 0.718]}
              />
              <mesh
                name="右摄像头1"
                castShadow
                receiveShadow
                geometry={nodes.右摄像头1.geometry}
                material={materials.material_3}
                position={[-4.574, 3.862, 0.109]}
              />
              <mesh
                name="右摄像头2"
                castShadow
                receiveShadow
                geometry={nodes.右摄像头2.geometry}
                material={materials.material_3}
                position={[-4.576, 3.867, 0.136]}
              />
              <mesh
                name="右摄像头3"
                castShadow
                receiveShadow
                geometry={nodes.右摄像头3.geometry}
                material={materials.material_3}
                position={[-4.576, 3.868, 0.138]}
              />
              <mesh
                name="右摄像头4"
                castShadow
                receiveShadow
                geometry={nodes.右摄像头4.geometry}
                material={materials['Mat_IOR_1.0_Dispersion分散0']}
                position={[-4.576, 3.868, 0.139]}
              />
              <group
                name="右腿旋转"
                position={[-4.599, 4.112, -0.386]}
                rotation={[Math.PI, -1.549, Math.PI]}
              >
                <mesh
                  name="右镜腿"
                  castShadow
                  receiveShadow
                  geometry={nodes.右镜腿.geometry}
                  material={materials.黑边框}
                  position={[-0.067, -1.222, -2.927]}
                  rotation={[0.125, 1.488, 2.809]}
                  scale={[0.216, 1.059, 0.159]}
                >
                  <mesh
                    name="可换电池"
                    castShadow
                    receiveShadow
                    geometry={nodes.可换电池.geometry}
                    material={materials.黑边框}
                    position={[0.021, 0.002, 0.066]}
                    scale={[4.63, 0.944, 6.275]}
                  />
                  <mesh
                    name="电源键"
                    castShadow
                    receiveShadow
                    geometry={nodes.电源键.geometry}
                    material={materials.material_3}
                    position={[0.021, -0.009, 0.066]}
                    scale={[0.939, 1.039, 1.039]}
                  />
                </mesh>
                <group name="电池片" position={[-0.11, -1.917, -7.405]} rotation={[-0.238, 0, 0]}>
                  <mesh
                    name="Cube"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube.geometry}
                    material={materials.电池片基础色}
                  />
                  <mesh
                    name="Cube_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube_1.geometry}
                    material={materials.电池片金属}
                  />
                </group>
              </group>
              <mesh
                name="左指示灯"
                castShadow
                receiveShadow
                geometry={nodes.左指示灯.geometry}
                material={materials['sunglass.002']}
                position={[4.047, 3.894, 0.164]}
              />
              <mesh
                name="左摄像头1"
                castShadow
                receiveShadow
                geometry={nodes.左摄像头1.geometry}
                material={materials.material_3}
                position={[4.236, 3.863, 0.108]}
              />
              <mesh
                name="左摄像头2"
                castShadow
                receiveShadow
                geometry={nodes.左摄像头2.geometry}
                material={materials.material_3}
                position={[4.239, 3.868, 0.137]}
              />
              <mesh
                name="左摄像头3"
                castShadow
                receiveShadow
                geometry={nodes.左摄像头3.geometry}
                material={materials.material_3}
                position={[4.239, 3.869, 0.138]}
              />
              <mesh
                name="左摄像头4"
                castShadow
                receiveShadow
                geometry={nodes.左摄像头4.geometry}
                material={materials['Mat_IOR_1.0_Dispersion分散0']}
                position={[4.239, 3.869, 0.139]}
              />
              <group
                name="左腿旋转"
                position={[4.281, 4.112, -0.392]}
                rotation={[-Math.PI, 1.484, -Math.PI]}
              >
                <mesh
                  name="左镜腿"
                  castShadow
                  receiveShadow
                  geometry={nodes.左镜腿.geometry}
                  material={materials.黑边框}
                  position={[-8.888, -0.356, -0.278]}
                  rotation={[1.41, 0.003, -0.072]}
                  scale={[0.216, 1.059, 0.159]}
                />
              </group>
              <mesh
                name="相机键"
                castShadow
                receiveShadow
                geometry={nodes.相机键.geometry}
                material={materials.material_3}
                position={[-4.573, 4.112, -0.172]}
              />
              <mesh
                name="鼻托孔"
                castShadow
                receiveShadow
                geometry={nodes.鼻托孔.geometry}
                material={materials.鼻托}
                position={[-0.612, 3.398, 0.565]}
              />
            </group>

            <group name="Empty006" position={[0, 0.372, 0]} rotation={[-1.549, 0, 0]} scale={0.579}>
              <group scale={1.5} position={[0, 0, -60]}>
                <TopPlane />
                <Neo />
              </group>
              <PerspectiveCamera
                name="Camera"
                makeDefault={true}
                far={1000}
                near={0.1}
                fov={26.2}
                position={[0, -0.098, 8.056]}
                scale={0.498}
              />
            </group>
          </group>
        </group>
      </group>
    </>
  );
}

useGLTF.preload('/20.glb');
