import { useGLTF } from '@react-three/drei';

export function Model3({ isVisible }) {
  const { nodes, materials } = useGLTF('/Model522-transformed.glb');
  return (
    <group visible={isVisible} position-z={8} dispose={null}>
      <group position={[-7.326, -0.204, 24.535]} rotation={[-Math.PI / 2, 0, 0.331]} scale={0.005}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71.geometry}
          material={materials.Scene_GroundTiles}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_1.geometry}
          material={materials.Scene_Checkered}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_2.geometry}
          material={materials.Scene_Pebbles}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_3.geometry}
          material={materials.Scene_StreetDecals}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_4.geometry}
          material={materials.Tree1_leaves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_5.geometry}
          material={materials['01___Default']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_6.geometry}
          material={materials.Airco_tex}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_7.geometry}
          material={materials.AlleyNet_Fence}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_8.geometry}
          material={materials.AlleyNet_Long_Tileable}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_9.geometry}
          material={materials.AlleyNet_Top_Net}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_10.geometry}
          material={materials.BakeryFlag}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_11.geometry}
          material={materials.Alley_plants}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_12.geometry}
          material={materials.BakerySign_tex}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_13.geometry}
          material={materials.Bakery_Long}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_14.geometry}
          material={materials.Bakery_Roof}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_15.geometry}
          material={materials.Bakery_Unique}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_16.geometry}
          material={materials.Bakery_Wall}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_17.geometry}
          material={materials.Bakery_Wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_18.geometry}
          material={materials.BambooFence_tex}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_19.geometry}
          material={materials.Bakery_Opacity}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_20.geometry}
          material={materials.Car_ToyotaTownace}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_21.geometry}
          material={materials.Dumpster_tex}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_22.geometry}
          material={materials.ElectricityPole_tex}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_23.geometry}
          material={materials.Hedge_Leaves_tex}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_24.geometry}
          material={materials.Hedge_tex}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_25.geometry}
          material={materials.Hotel_Long_Tileable1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_26.geometry}
          material={materials.PlantStore_Decals}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_27.geometry}
          material={materials.Hotel_Long_Tileable2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_28.geometry}
          material={materials.Hotel_Opacity}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_29.geometry}
          material={materials.Hotel_Roofs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_30.geometry}
          material={materials.Hotel_Unique}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_31.geometry}
          material={materials.Hotel_Walls}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_32.geometry}
          material={materials.Lantern_tex}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_33.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_34.geometry}
          material={materials.Plant1_Pot}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_35.geometry}
          material={materials.Plant1_leaves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_36.geometry}
          material={materials.Plant3_Pot}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_37.geometry}
          material={materials.PlantStore_Ivy}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_38.geometry}
          material={materials.Plant3_leaves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_39.geometry}
          material={materials.PlantFlower2_leaves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_40.geometry}
          material={materials.PlantStore_Leaking}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_41.geometry}
          material={materials.PlantStore_Long_Tileable}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_42.geometry}
          material={materials.PlantStore_Long_Tileable2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_43.geometry}
          material={materials.PlantStore_Opacity}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_44.geometry}
          material={materials.PlantStore_Roof}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_45.geometry}
          material={materials.PlantStore_Unique}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_46.geometry}
          material={materials.PlantStore_Unique2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_47.geometry}
          material={materials.PlantStore_Leaves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_48.geometry}
          material={materials.PlantStore_Walls}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_49.geometry}
          material={materials.Posters_tex}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_50.geometry}
          material={materials.Prop_Gate_tex}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_51.geometry}
          material={materials.Railroad_Bars}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_52.geometry}
          material={materials.Railroad_Cobble}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_53.geometry}
          material={materials.Railroad_Concrete}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_54.geometry}
          material={materials.Railroad_ElPole}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_55.geometry}
          material={materials.Railroad_bricks}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_56.geometry}
          material={materials.Scene_Bricks}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_57.geometry}
          material={materials.PlantStore_Opacity2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_58.geometry}
          material={materials.Scene_Concrete}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_59.geometry}
          material={materials.Scene_ConcreteBlocks}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_60.geometry}
          material={materials.Scene_Dirt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_61.geometry}
          material={materials.Scene_Road}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_62.geometry}
          material={materials.Scene_TileableWood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_63.geometry}
          material={materials.Scene_Water}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_64.geometry}
          material={materials.TrafficSign_tex}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_65.geometry}
          material={materials.Railroad_Ballast}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_66.geometry}
          material={materials.TrainGate_tex}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_67.geometry}
          material={materials.TrainTrafficSign_Tex}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_68.geometry}
          material={materials.Tree1_trunk}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_69.geometry}
          material={materials.Tree2_Tex}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_70.geometry}
          material={materials.TreePlot_tex}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_71.geometry}
          material={materials.VendingMachine2_Tex}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_72.geometry}
          material={materials.VendingMachine3_Tex}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71_73.geometry}
          material={materials.Railroad_Track}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/Model522-transformed.glb');
