/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Model3({ isVisible }) {
  const { nodes, materials } = useGLTF('/Model512-transformed.glb');
  return (
    <group dispose={null} position={[0, 0, 8]} visible={isVisible}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.Scene_Checkered}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.Scene_Pebbles}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials.Scene_StreetDecals}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_13.geometry}
        material={materials.Tree1_leaves}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials['01___Default']}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_15.geometry}
        material={materials.Airco_tex}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_16.geometry}
        material={materials.AlleyNet_Fence}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_17.geometry}
        material={materials.AlleyNet_Long_Tileable}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials.AlleyNet_Top_Net}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_19.geometry}
        material={materials.BakeryFlag}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.Alley_plants}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials.BakerySign_tex}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_21.geometry}
        material={materials.Bakery_Long}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_22.geometry}
        material={materials.Bakery_Roof}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_23.geometry}
        material={materials.Bakery_Unique}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_24.geometry}
        material={materials.Bakery_Wall}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_25.geometry}
        material={materials.Bakery_Wood}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_26.geometry}
        material={materials.BambooFence_tex}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_3.geometry}
        material={materials.Bakery_Opacity}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_30.geometry}
        material={materials.Car_ToyotaTownace}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_31.geometry}
        material={materials.Dumpster_tex}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_32.geometry}
        material={materials.ElectricityPole_tex}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      /> */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_35.geometry}
        material={materials.Hedge_Leaves_tex}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_38.geometry}
        material={materials.Hedge_tex}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_39.geometry}
        material={materials.Hotel_Long_Tileable1}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.PlantStore_Decals}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_40.geometry}
        material={materials.Hotel_Long_Tileable2}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_41.geometry}
        material={materials.Hotel_Opacity}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_42.geometry}
        material={materials.Hotel_Roofs}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_43.geometry}
        material={materials.Hotel_Unique}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_44.geometry}
        material={materials.Hotel_Walls}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_45.geometry}
        material={materials.Lantern_tex}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_46.geometry}
        material={materials.material}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_47.geometry}
        material={materials.Plant1_Pot}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_48.geometry}
        material={materials.Plant1_leaves}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_49.geometry}
        material={materials.Plant3_Pot}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials.PlantStore_Ivy}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_50.geometry}
        material={materials.Plant3_leaves}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_52.geometry}
        material={materials.PlantFlower2_leaves}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_53.geometry}
        material={materials.PlantStore_Leaking}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_54.geometry}
        material={materials.PlantStore_Long_Tileable}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_55.geometry}
        material={materials.PlantStore_Long_Tileable2}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_56.geometry}
        material={materials.PlantStore_Opacity}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_57.geometry}
        material={materials.PlantStore_Roof}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_58.geometry}
        material={materials.PlantStore_Unique}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_59.geometry}
        material={materials.PlantStore_Unique2}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.PlantStore_Leaves}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_60.geometry}
        material={materials.PlantStore_Walls}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_61.geometry}
        material={materials.Posters_tex}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_62.geometry}
        material={materials.Prop_Gate_tex}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_63.geometry}
        material={materials.Railroad_Bars}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_64.geometry}
        material={materials.Railroad_Cobble}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_65.geometry}
        material={materials.Railroad_Concrete}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_66.geometry}
        material={materials.Railroad_ElPole}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_67.geometry}
        material={materials.Railroad_bricks}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_68.geometry}
        material={materials.Scene_Bricks}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_7.geometry}
        material={materials.PlantStore_Opacity2}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_70.geometry}
        material={materials.Scene_Concrete}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_71.geometry}
        material={materials.Scene_ConcreteBlocks}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_72.geometry}
        material={materials.Scene_Dirt}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_73.geometry}
        material={materials.Scene_GroundTiles}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_74.geometry}
        material={materials.Scene_Road}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_76.geometry}
        material={materials.Scene_TileableWood}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_77.geometry}
        material={materials.Scene_Water}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_79.geometry}
        material={materials.TrafficSign_tex}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.Railroad_Ballast}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_80.geometry}
        material={materials.TrainGate_tex}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_81.geometry}
        material={materials.TrainTrafficSign_Tex}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_82.geometry}
        material={materials.Tree1_trunk}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_83.geometry}
        material={materials.Tree2_Tex}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_84.geometry}
        material={materials.TreePlot_tex}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_85.geometry}
        material={materials.VendingMachine2_Tex}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_86.geometry}
        material={materials.VendingMachine3_Tex}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_9.geometry}
        material={materials.Railroad_Track}
        position={[-7.326, -0.204, 24.535]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={0.005}
      />
    </group>
  );
}

useGLTF.preload('/Model512-transformed.glb');
